---
- hosts: all
  gather_facts: false
  tasks:
  - name: Create local 'docker' group
    delegate_to: localhost
    group:
      name: docker
    register: docker_group
  - debug: var=docker_group
  - name: Create local 'jenkins' user in 'docker' secondary group
    delegate_to: localhost
    user: 
      name: jenkins
      comment: Jenkins Docker host user
      groups: docker
  - name: Check that we're running as 'jenkins'
    delegate_to: localhost
    fail: msg="Not running as 'jenkins'"
    when: lookup('env','USER') != 'jenkins'
  - name: Create a Jenkins docker container
    delegate_to: localhost
    docker_container:
      name: jenkins
      image: jenkinsci/blueocean
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/home/jenkins/jenkins_home
      published_ports:
      - 8080:8080
      - 50000:50000
    register: docker_container_info
  - debug: var=docker_container_info